✨ [Feature/Domain-27] Domain Vo Wrapping  진행
jung-dam-diary/team-angelbaby-jungdam-be pull request #28
Opened 2021-12-07 15:37 UTC by DongGeon0908

## 💡 개요 

- resolved #27 
- 전체 도메인에 대한 Wrapping 작업 진행

## 📑 작업 사항 

- Member Domain을 제외한 다른 Domain에 대한 Wrapping 작업 진행

## ✒️ 코드 리뷰 요청 사항

- Wrapping이 정상적으로 되었는지 확인해주세요!

## ✔️ 코드 리뷰 반영 사항

2021-12-07 17:27 UTC, soo5717 requested changes
코드 양이 많았는데 작성하시느라 진짜 고생 많으셨어요! **천재구피 😝**

쭉 한 번 봤는데 큰 이슈는 없었습니다. 대신 대소문자 변경해야 하는 부분이랑 칼럼이 잘못 들어간 부분이 있어서 그 부분만 변경해주시면 될 것 같습니다👍

2021-12-07 17:27 UTC, soo5717 commented on src/main/java/com/jungdam/diary/domain/vo/Title.java
> +    @Column(name = "diary_title")
다이어리 제목은 글자수 제한 없이 가나요?

2021-12-07 17:27 UTC, soo5717 commented on src/main/java/com/jungdam/diary_image/domain/DiaryPhoto.java
>      @GeneratedValue(strategy = GenerationType.IDENTITY)
20번째 줄에 diary_image_id로 되어있는데 diary_photo_id로 변경해야 할 것 같습니다!!
```java
@Column(name = "diary_image_id")
```

2021-12-07 17:27 UTC, soo5717 commented on src/main/java/com/jungdam/emoji/domain/Emoji.java
>      @JoinColumn(name = "member_Id")
소문자로 변경해야 합니다! 34번째 줄도 변경 필요해요~
```suggestion
    @JoinColumn(name = "member_id")
```

2021-12-08 02:52 UTC, dlfdyd96 approved these changes
고생하셨습니다! 도메인에 validation 을 거는 작업은 해보면 좋다고 하셔서 직접 해보고싶네요 빨리 두근두근 😊

2021-12-08 02:52 UTC, dlfdyd96 commented on src/main/java/com/jungdam/album/domain/vo/FamilyMotto.java
> +
이부분에 familly Motto 의 길이를 제한하는 validation이 필요하단 말씀이시죵?

2021-12-08 05:46 UTC, DongGeon0908 commented on src/main/java/com/jungdam/album/domain/vo/FamilyMotto.java
> +
넵 validate 메서드를 만들고 생성자에서 check하면 좋을 것 같습니다!

2021-12-08 05:46 UTC, DongGeon0908 commented on src/main/java/com/jungdam/emoji/domain/Emoji.java
>      @JoinColumn(name = "member_Id")
역시 천재 주디!!!

2021-12-08 05:49 UTC, dlfdyd96 approved these changes
우앙 빠뜨리지 않으셧군용 👍🏻

2021-12-08 05:49 UTC, dlfdyd96 commented on src/main/java/com/jungdam/diary/domain/vo/Title.java
> +    @Column(name = "diary_title", length = 30)
빠뜨리지 않으셧군용 👍🏻

2021-12-08 05:50 UTC, soo5717 approved these changes

2021-12-08 05:50 UTC, merged