👔 [Feature/participant-40] 멤버 리스트 조회
jung-dam-diary/team-angelbaby-jungdam-be pull request #77
Opened 2021-12-14 18:14 UTC by dlfdyd96

## 💡 개요 

- resolved #40 

## 📑 작업 사항 

![image](https://user-images.githubusercontent.com/43674132/146056091-c5f36212-b227-46df-b467-13ed2cda0402.png)

- 앨범의 멤버 리스트 조회 기능
- 앨범의 멤버 리스트가 아닌 회원이 조회 시 `NOT_EXIST_PARTICIPANT` 예외 발생

## ✒️ 코드 리뷰 요청 사항

## ✔️ 코드 리뷰 반영 사항

2021-12-14 18:36 UTC, DongGeon0908 approved these changes
Dto내부에 다른 Dto를 추가하셨는데, 변경사항이 존재한다면 위험할 것 같아요!

2021-12-14 18:36 UTC, DongGeon0908 commented on src/main/java/com/jungdam/participant/converter/ParticipantConverter.java
> +        List<ReadParticipantResponse> readParticipantResponses = participants.stream().map(p ->
.map을 밑으로 보내는게 좋을 것 같아요!

2021-12-14 18:36 UTC, DongGeon0908 commented on src/main/java/com/jungdam/participant/converter/ParticipantConverter.java
> +                .participantRole(p.getRole().name())
이부분은 추후에 get..Value로 바꿔야 될 것 같습니다!

2021-12-14 18:36 UTC, DongGeon0908 commented on src/main/java/com/jungdam/participant/domain/Participant.java
> +
getNicknameValue가 맞을 것 같아요!
밑의 getter도요!!

2021-12-14 18:36 UTC, DongGeon0908 commented on src/main/java/com/jungdam/participant/dto/response/ReadAllParticipantResponse.java
> +    private final List<ReadParticipantResponse> participants;
단건조회와 전체조회 사이에 필드값이 변경된다면, 해당 코드에서 문제가 발생할 것 같습니다!

2021-12-14 18:36 UTC, DongGeon0908 commented on src/main/java/com/jungdam/participant/facade/ParticipantFacade.java
> +        }
저도 if문을 퍼사드에서 사용했느데.. 이게 조금 찜찜하긴해요 ㅜㅜ
@soo5717 

service에서 throw 되는 로직을 구성하고 퍼사드에 가져다 쓰는게 좋을지.. 아니면 퍼사드에서 exception을 터트릴지 정하면 좋을 것 같아요!

2021-12-14 18:41 UTC, dlfdyd96 commented on src/main/java/com/jungdam/participant/dto/response/ReadAllParticipantResponse.java
> +    private final List<ReadParticipantResponse> participants;
흠 맞아요 ㅠㅠ 이 부분이 가장 고민이 컸었는데 
```json
{
  "participants" : [ {1}, {2} ]
}
```

이렇게 담아내고 싶었는데 `ReadParticipantResponse`말고 다른 대안이 있을 까요?

2021-12-15 08:01 UTC, soo5717 requested changes
조금씩 수정 해야 할 부분들이 있어서 수정 후 머지 해주시면 좋을 것 같습니다!
일급 컬렉션 부분은 저도 참고할게요~

2021-12-15 08:01 UTC, soo5717 commented on src/main/java/com/jungdam/participant/domain/Participant.java
> +    }
닉네임 부분 @Embedded로 Wrapping 안된 것 같은데 확인 후 변경해주세요~

2021-12-15 08:01 UTC, soo5717 commented on src/main/java/com/jungdam/participant/dto/response/ReadParticipantResponse.java
> +    private final String participantRole;
그냥 email, nickname 이런 식으로 변수명 바꿔도 될 것 같습니다.

response 확인해보니까 아래와 같은 구성이라 participant를 접두사로 붙이는건 불필요한 중복인 것 같습니다!
```json
{
    "participants" : [
        {
            "participantEmail" : "test@naver.com"
        }
    ]
}
```

2021-12-15 08:01 UTC, soo5717 commented on src/main/java/com/jungdam/participant/dto/response/ReadParticipantResponse.java
> +            final String participantNickname) {
변수명 변경 후에 이런 줄 바꿈도 한 번 더 확인해주세요!

2021-12-15 08:01 UTC, soo5717 commented on src/main/java/com/jungdam/participant/facade/ParticipantFacade.java
> +    private final ParticipantConverter participantConverter;
저 같은 경우는 converter를 가장 위에 올리고, participantFacade니까 participantService부터 시작해서 필요한 순서대로 나열했습니다~ 이건 그냥 옵션 사항이라 참고만 하시면 될 것 같아요!

2021-12-15 08:01 UTC, soo5717 commented on src/main/java/com/jungdam/participant/facade/ParticipantFacade.java
> +    @Transactional
조회만 하는 경우는 readOnly 추가해주세요!

2021-12-15 08:01 UTC, soo5717 commented on src/main/java/com/jungdam/participant/facade/ParticipantFacade.java
> +    public ReadAllParticipantResponse getAll(ReadAllParticipantBundle bundle) {
```
controller -> C(create)R(getOne getAll)U(update)D(delete)
service -> C(insert)R(find findAll)U(update)D(delete)
```

저희 원래 정했던 컨벤션이 위에 내용인데 중간에 facade가 있어서 저 같은 경우는 아래처럼 진행 중에 있습니다.
@dlfdyd96 @DongGeon0908 

```
controller -> C(create)R(getOne getAll)U(update)D(delete)
facade-> C(insert)R(find findAll)U(update)D(delete)
service -> JPA 방식 C(save)
```

2021-12-15 08:01 UTC, soo5717 commented on src/main/java/com/jungdam/participant/presentation/ParticipantController.java
> +    @GetMapping()
() 안 달아도 될 것 같습니다.

2021-12-15 08:01 UTC, soo5717 commented on src/main/java/com/jungdam/participant/facade/ParticipantFacade.java
> +        }
저는 service에서 throw 로직 구성하고 퍼사드에서 가져다 쓰는 방식이 좋은 것 같습니다!

2021-12-15 08:01 UTC, soo5717 commented on src/main/java/com/jungdam/participant/facade/ParticipantFacade.java
> +        if (participantService.notExistsByAlbumAndMember(album, member)) {
긍정 조건 👍

2021-12-15 08:01 UTC, soo5717 commented on src/main/java/com/jungdam/participant/converter/ParticipantConverter.java
> +                    .participantRole(p.getRole().name())
. 한 번만 쓰도록 변경 할 수 있으면 변경 하는게 좋을 것 같습니다!

2021-12-15 08:05 UTC, dlfdyd96 commented on src/main/java/com/jungdam/participant/dto/response/ReadParticipantResponse.java
> +    private final String participantRole;
아하 맞네요 중복때문에 접두사를 때는게 좋을 것 같아요

2021-12-15 08:07 UTC, dlfdyd96 commented on src/main/java/com/jungdam/participant/domain/Participant.java
> +    }
VO 처리가 안되었네용 수정하고 올릴께요!

2021-12-15 13:58 UTC, dlfdyd96 commented
리뷰를 해주셔서 감사합니다 열허분! 다만 주디가 언급해주셨던 [리뷰](https://github.com/jung-dam-diary/team-angelbaby-jungdam-be/pull/77#discussion_r769351995) 에 대해서는 생각해보다가 지금은 도저히 생각이 안나더라구용 ㅎㅎ refactoring에 남겨 두겠습니닷

2021-12-15 14:00 UTC, DongGeon0908 approved these changes
굳굳입니당!

2021-12-15 14:00 UTC, DongGeon0908 commented on src/main/java/com/jungdam/participant/converter/ParticipantConverter.java
> +                    .participantRole(p.getRole().name())
메서드를 분리해서 진행하면 .을 한번만 사용할 수 있을 것 같아요!
아니면 다른 class에서 switching해주는 로직이 있어도 가능할 것 같기도 하구요!!

2021-12-15 14:02 UTC, dlfdyd96 commented on src/main/java/com/jungdam/participant/facade/ParticipantFacade.java
> +        if (participantService.notExistsByAlbumAndMember(album, member)) {
이 부분은 구피 코드랑 겹칠 것 같아서 구피께 merge가 되면 수정하고 다시 PR -> Merge 진행하겠습니다!

2021-12-15 15:40 UTC, DongGeon0908 approved these changes
큰 리스크가 있는 부분만 comment 남겼습니다!

2021-12-15 15:40 UTC, DongGeon0908 commented on src/main/java/com/jungdam/participant/domain/vo/Nickname.java
> +    }
무엇이죵

2021-12-15 15:40 UTC, DongGeon0908 commented on src/main/java/com/jungdam/participant/domain/vo/Role.java
> +    ;
수정부탁드려요~

2021-12-15 15:49 UTC, merged